### PR TITLE
Change csp ID

### PR DESCRIPTION
**Pull request by sasataku**
This PR changes the CSP ID of Zero and Pico for actual operation.

### CODE REVIEW

**Review by yashi — COMMENTED** [review]
I'm not sure why I'm selected as a reviewer. What was the reason behind this change?

**Comment by sasataku** [comment]
> I'm not sure why I'm selected as a reviewer. What was the reason behind this change?

Sorry for the inconvenience, but since you’re the code owner, you’ve been automatically assigned as a reviewer.
The CSP ID has already been reviewed by the SC-Sat1 team, so you don't need to review it.

The reason this PR hasn’t been merged yet is that I'm waiting for the following PR to be merged.

https://github.com/libcsp/libcsp/pull/722

It appears that it has already been merged, so I will merge this PR.

**Comment by yashi** [comment]
I'm totally lost. CSP ID is nothing to do with `-Wpedantic`. or are you saying that you were wating for CI to be green?

**Comment by sasataku** [comment]
Sorry for the lack of explanation. I was waiting for the CI to pass. Since tests with Twister on Pico include the `-Werror` option, warnings were detected as errors. I was waiting to merge to confirm that the change in the CSP ID would not cause the Twister tests to fail.

**Pull request merged**
