### PR TITLE
zero: meta-csp: Add RAW format image capture capability for SC-Sat1

### PR DESCRIPTION
**Pull request by moonlight83340**
Implemented functionality to capture raw images using the camera on scsat1.

Modified the camera service to use `libcamerify` in front of the program to ensure compatibility of V4L2 code with libcamera.

Utilized `v4l2` for direct image capture from the camera.

This adds the capability to capture raw images from the camera on scsat1.

### CODE REVIEW

**Comment by yashi** [comment]
Why do we have to use v4l2??

**Comment by moonlight83340** [comment]
> Why do we have to use v4l2??

We tougth it would be simplier to develop with it. We can use directly libcamera library with `c++`.

**Comment by yashi** [comment]
Easy for you to implement even though it doesn't support everything libcamera supports?

**Comment by moonlight83340** [comment]
> Easy for you to implement even though it doesn't support everything libcamera supports?

I tougth writing a `V4l2` `c` code would be easier to understand, I will take a look at `c++` code in my free time to see if I can make a simple app taking capture and see how it's going on with the `c++` app.

**Pull request closed without merging**
